server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5436/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: minha-chave-super-secreta-de-32-caracteres-ou-mais

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
